### ISSUE TITLE
Does not build

### ISSUE THREAD

**Issue by pumoica** [shmuelhizmi/web-desktop-environment#10]
Great concept. However, following the build/install instructions here https://github.com/shmuelhizmi/web-desktop-environment (both quick start and advanced run) and here https://github.com/shmuelhizmi/web-desktop-environment/tree/master/packages/servers/development-edition-server only leads in getting a bunch of different build errors.  

Tried all mentioned options in a windows and a linux boxes and against the master branch and the tag 1.0.2 same outcome.

Are these instructions up to date and/or accurate?

**Comment by shmuelhizmi** [comment]
@pumoica hey, sorry for the delay, have you been using npm version 7 or higher?

**Comment by pumoica** [comment]
@shmuelhizmi , thank you for coming back on this. I deleted my local copy of your repo, so had to re-create it. To answer your question, yes I use npm 7. The gist of all the issues I encountered is that your project has a number of dependencies that aren't explicitly mentioned in the instructions but are necessary for a successful build. Some of them (e.g. code-server) expect you to run your project on a unix box (the mentioned code-server project tries to execute postinstall.sh).

Anyway, I was able to build and run the project locally using your Dockerfile.

**Comment by shmuelhizmi** [comment]
@pumoica the reason some dependencies are not mentioned in the root package.json is that we are using NPM workspaces, running npm install should not only install all packages from the root package.json but also from every sub-package.
but you are completely right that I should have mentioned that you need LINUX or OSX box to build the project.
