### ISSUE TITLE
Adding access control to endpoints

### ISSUE THREAD

**Issue by drvladb** [shmuelhizmi/web-desktop-environment#19]
I wish to [web-desktop-environment](https://github.com/shmuelhizmi/web-desktop-environment) in Docker form as a multi tenant development environment but cannot figure out a way to safeguard the endpoints so that only I (and people given access) are able to use it. I already have a setup with [vouch proxy](https://github.com/vouch/vouch-proxy) but cannot figure out how to integrate it. It would be preferable if there was an option to use domains instead of ports or some kind of password mechanism.

**Comment by shmuelhizmi** [comment]
Hey, I am currently working on a way to secure your desktop via password while exposing only only one public port instead of many like the current implementation.
As for using a domain url instead of a up address, you can actually already do that right now but entering a port will always be required.

**Comment by drvladb** [comment]
Sounds cool, can't wait to see it!

**Comment by alexfornuto** [comment]
I'm also interesting in trying this project in a secured way. I'm trying to proxy behind [Pomerium](https://github.com/pomerium/pomerium), and access it directly from a VM instead of going through web-desktop.run.

Is it possible currently to access the DE without using web-desktop.run?

**Comment by shmuelhizmi** [comment]
@alexfornuto you can run the web interface locally by installing the repo on your computer and following the instructions [here](https://github.com/shmuelhizmi/web-desktop-environment#advanced-run), in terms of security note that "web-desktop.run" does not send information to anywhere but your server and can even work offline using web caching!

**Comment by alexfornuto** [comment]
@shmuelhizmi is "web-desktop.run" the client or the server in that context? In my ideal environment, nothing would run from my local computer, and I could access the web desktop running on my VM from any device,

**Comment by shmuelhizmi** [comment]
@alexfornuto  "web-desktop-environment" is made up of two parts, a server to install on the PC or VM you want to control and a client web app that you can host yourself or access from web-desktop.run , if you want to self host the client you can learn how to do it from my last comment

**Comment by alexfornuto** [comment]
Thanks @shmuelhizmi. I'm very new to the concept, but having just set up Guacamole for SSH-over-browser access, I now have a better mental reference point for these concepts.

**Comment by shmuelhizmi** [comment]
hey along side the v2 release everything now should be contained under one end point :)
thanks for opening this issue 👍🏽
