### ISSUE TITLE
Console error

### ISSUE THREAD

**Issue by crispyi2** [shmuelhizmi/web-desktop-environment#4]
when i was trying to access the server from the website https://web-desktop.app/ that i had started up (which i used goormide to host) gave me this error and a white screen:
------------------------------------------------------------------------------------------------------------------------------------------------------------------------
websocket.js:124 Mixed Content: The page at 'https://www.web-desktop.app/' was loaded over HTTPS, but attempted to connect to the insecure WebSocket endpoint 'ws://https/socket.io/?EIO=3&transport=websocket'. This request has been blocked; this endpoint must be available over WSS.
h.doOpen @ websocket.js:124
------------------------------------------------------------------------------------------------------------------------------------------------------------------------
I was using the development server btw. plz help

**Comment by shmuelhizmi** [comment]
'ws://https/socket.io/?EIO=3&transport=websocket' seems like a broken URL, I assume your server was running on localhost:5000, did you leave the server host at localhost and port at port 5000?

**Comment by crispyi2** [comment]
no it isn't running at localhost but the port is set to 5000

**Comment by shmuelhizmi** [comment]
ok, working on a fix now

**Comment by shmuelhizmi** [comment]
@crispyi2 FIXED, you can now access your server from http.web-desktop.run , the new web-desktop-environment site url

**Comment by crispyi2** [comment]
ok
